project:
  type: website
  output-dir: ../_site

website:
  title: "Julia modeling"
  repo-url: https://github.com/sosiristseng/jl-modeling
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/sosiristseng/jl-modeling
        text: GitHub repo
  sidebar:
    style: docked
    contents: auto

format:
  html:
    theme:
      light: cosmo
      dark: slate
    grid:
      sidebar-width: 350px
    toc: true
