name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-manifest.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ID: '189113' # https://github.com/apps/wen-wei-s-pr-bot
  IMG: 'app:test'

jobs:
  update-manifest:
    strategy:
      matrix:
        dir:
          - diffeq
          - catalyst
          - pde
          - visual
      fail-fast: false
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Update Julia dependencies
        run: >
          docker run --rm -w /tmp
          -v ${{ github.workspace }}:/tmp
          -e JULIA_PKG_PRECOMPILE_AUTO=0
          julia:latest
          julia --project=docs/${{ matrix.dir }} --color=yes -e 'import Pkg; Pkg.update()'
      # Authenticate with a custom GitHub APP
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - name: Generate token for PR
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          title: Julia Dependency Update for ${{ matrix.dir }}
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-${{ matrix.dir }}
          labels: |
            automerge
